name: Update Rollhockey Tabellen

on:
  schedule:
    - cron: "0 * * * *"  # jede Stunde
  workflow_dispatch:     # manuelles Testen möglich



jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: npm install
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Puppeteer installieren
        run: npm install puppeteer

      - name: Tabellen aktualisieren
        run: node scripts/updateData.js

      - name: Änderungen committen & pushen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/data/
          git commit -m "Auto update Tabellen" || echo "Keine Änderungen"
          git push
